### PR TITLE
Fix command hint text

### LINKED ISSUE #113: Update the help text to show "" vs [] for command params
#### Summary
The current hint text is misleading/confusing to users as it leads them to think that the parameters should be in [] vs ""

#### Steps to reproduce
1. Type /poll to see the hint text

#### Expected behavior
Users would benefit from seeing the following hint: 

> /poll "Question" "Answer 1" "Answer 2" ...

instead of

> /poll [Question] [Answer 1] [Answer 2] ...

#### Observed behavior (that appears unintentional)
What did you see happen? Please include relevant error messages and/or screenshots.

#### Server configuration
**Operating system:**
Any
**Mattermost version:**
Any
**Matterpoll version:**
Latest
**Updated from an older Matterpoll version or fresh install:**
Fresh install
<details>
<summary>Mattermost server logs</summary>

```
Insert your Mattermost server logs here
```
</details>

### PR DESCRIPTION
**Pull request by kaakaa**
Fix auto comoplete hing.

Fixes #113

### CODE REVIEW

File: server/plugin/command.go [hunk 1]
```diff
@@ -96,6 +96,6 @@ func getCommand(trigger string) *model.Command {
 		Description:      "Polling feature by https://github.com/matterpoll/matterpoll",
 		AutoComplete:     true,
 		AutoCompleteDesc: "Create a poll",
-		AutoCompleteHint: "[Question] [Answer 1] [Answer 2]...",
+		AutoCompleteHint: `"Question" "Answer 1" "Answer 2"...`,
```
Comment (hanzei) [inline server/plugin/command.go]: As discussed in https://github.com/matterpoll/matterpoll/issues/113 this should be changed.
```suggestion
		AutoCompleteHint: `"[Question]" "[Answer 1]" "[Answer 2]"...`,
```
